[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["Sina Ehsanzadeh <s.eh.81088135@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
poetry-core = "^2.2.1"
python-dotenv = "^1.1.1"
sqlalchemy = "^2.0.45"
alembic = "^1.17.2"
psycopg = {extras = ["binary"], version = "^3.3.2"}
pytest = "^9.0.2"
fastapi = "^0.126.0"
uvicorn = "^0.38.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
