from abc import ABC, abstractmethod

class ProjectRepository(ABC):
    @abstractmethod
    def add(self, data: dict) -> int: ...
    @abstractmethod
    def get(self, project_id: int): ...
    @abstractmethod
    def delete(self, project_id: int): ...

class TaskRepository(ABC):
    @abstractmethod
    def add(self, data: dict) -> int: ...
    @abstractmethod
    def get(self, task_id: int): ...
    @abstractmethod
    def list_by_project(self, project_id: int): ...
    @abstractmethod
    def update(self, task_id: int, data: dict): ...
    @abstractmethod
    def delete(self, task_id: int): ...
